package com.kulchaflo.tv.mk2.gv.youtube

object YouTubePolicyConstants {
    const val YOUTUBE_POINTER_IDLE_HIDE_MS = 2500L
    const val BROWSER_FULLSCREEN_POINTER_IDLE_HIDE_MS = 2500L
    const val YOUTUBE_BACK_DEBOUNCE_MS = 450L
    const val YOUTUBE_FULLSCREEN_CHAT_COLLAPSE_MIN_INTERVAL_MS = 900L

    const val YOUTUBE_PREMIUM_POPUP_MAX_CHECKS_LOCATION_WINDOW = 3
    const val YOUTUBE_PREMIUM_POPUP_MAX_CHECKS_FULLSCREEN_WINDOW = 5
    const val YOUTUBE_PREMIUM_POPUP_DISMISS_COOLDOWN_MS = 60_000L
    const val YOUTUBE_PREMIUM_POPUP_INTERACTION_BURST_MIN_INTERVAL_MS = 1000L

    const val YOUTUBE_QUALITY_HELPER_MAX_ATTEMPTS_PER_URL = 3
    const val YOUTUBE_QUALITY_HELPER_COOLDOWN_MS = 12_000L
    const val YOUTUBE_QUALITY_HELPER_VERIFY_FOLLOW_UP_DELAY_MS = 4_000L

    // YouTube smart auto-fullscreen timing constants (media-ready policy)
    const val YOUTUBE_AUTO_FULLSCREEN_AFTER_MEDIA_READY_MS = 1500L
    const val YOUTUBE_AUTO_FULLSCREEN_RETRY_1_MS = 3000L
    const val YOUTUBE_AUTO_FULLSCREEN_RETRY_2_MS = 6000L
    const val YOUTUBE_AUTO_FULLSCREEN_ABSOLUTE_FALLBACK_MS = 10000L
    const val YOUTUBE_AUTO_FULLSCREEN_CALLBACK_WAIT_MS = 1500L
    const val YOUTUBE_AUTO_FULLSCREEN_CONTROLS_REVEAL_TO_BUTTON_DELAY_MS = 650L
    const val YOUTUBE_AUTO_FULLSCREEN_TARGET_PROBE_TIMEOUT_MS = 1150L
    const val YOUTUBE_AUTO_FULLSCREEN_TARGET_PROBE_RETRY_DELAY_MS = 850L
    const val YOUTUBE_AUTO_FULLSCREEN_TARGET_PROBE_MAX_PASSES_PER_ATTEMPT = 3
    const val YOUTUBE_AUTO_FULLSCREEN_OVERLAY_RETRY_DELAY_MS = 900L
    const val YOUTUBE_AUTO_FULLSCREEN_AD_DEFER_DELAY_MS = 2000L
    const val YOUTUBE_AUTO_FULLSCREEN_MAX_OVERLAY_DEFERRALS = 4
    const val YOUTUBE_AUTO_FULLSCREEN_MAX_ATTEMPTS = 3

    const val YOUTUBE_FULLSCREEN_CONTROLS_REVEAL_X_RATIO = 620f / 1920f
    const val YOUTUBE_FULLSCREEN_CONTROLS_REVEAL_Y_RATIO = 420f / 1080f
    const val YOUTUBE_FULLSCREEN_BUTTON_X_RATIO = 1210f / 1920f
    const val YOUTUBE_FULLSCREEN_BUTTON_Y_RATIO = 760f / 1080f
    const val YOUTUBE_FULLSCREEN_CONTROLS_REVEAL_X_FALLBACK = 620f
    const val YOUTUBE_FULLSCREEN_CONTROLS_REVEAL_Y_FALLBACK = 420f
    const val YOUTUBE_FULLSCREEN_BUTTON_X_FALLBACK = 1210f
    const val YOUTUBE_FULLSCREEN_BUTTON_Y_FALLBACK = 760f
}
